name = "CyclotomicNumbers"
uuid = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.3"

[deps]
ModuleElts = "4249f315-58d4-4c46-b324-3577fc7dfca0"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
#SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf" uncomment if :svec

[compat]
ModuleElts = "0.1"
Primes = "0.5.3, 0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
