name = "Cyclotomics"
uuid = "c380f8b6-65b3-4789-a31b-7d6b5dc6d4c5"
authors = ["Jean Michel <jean.michel@imj-prg.fr>"]
version = "0.1.0"

[deps]
ModuleElts = "4249f315-58d4-4c46-b324-3577fc7dfca0"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
